@startuml
'https://plantuml.com/sequence-diagram

autonumber
Master_python -> Slave_c: Raise the Impactor (message)
Slave_c --> Master_python: Response that comand was succesful (message)

Master_python -> Slave_c: Height to which raise the Impactor [int]
Slave_c --> Master_python: Response that Impartor have been raised to designated height (message)

Master_python -> Slave_c: Drop the Impactor (message)
Slave_c --> Master_python: Response that Impactor was detached (message)

Slave_c --> Master_python: Send time difference from photocell [int]
Slave_c --> Master_python: Send time at which the experiment ended [int]
Slave_c --> Master_python: accelerometer data [table]

Slave_c --> Master_python: Experiment ended and data was sent (message)
@enduml